/*
* generated by Xtext
*/
package org.dadacoalition.pireditor.ui.contentassist;

import org.dadacoalition.pireditor.ui.contentassist.AbstractPirProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PirProposalProvider extends AbstractPirProposalProvider {

}
