/*
 * generated by Xtext
 */
package org.dadacoalition.pireditor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PirRuntimeModule extends org.dadacoalition.pireditor.AbstractPirRuntimeModule {

}
