/*
 * generated by Xtext
 */
package org.dadacoalition.pireditor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PirUiModule extends org.dadacoalition.pireditor.ui.AbstractPirUiModule {
	public PirUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
